version: '3.0.{build}'
image: Visual Studio 2022
configuration: Release
branches:
  only:
  - master
skip_commits:
  files:
    - README.md
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: pip install antlr4-tools
  - cmd: dotnet --version
  - cmd: dotnet restore --verbosity m
build_script:
  - cmd: dotnet pack /p:PackageVersion=%APPVEYOR_BUILD_VERSION% ./src/NCalc/NCalc.csproj
clone_depth: 1
test_script:
  - cmd: dotnet restore --verbosity m
  - cmd: dotnet test ./test/NCalc.Tests/NCalc.Tests.csproj
artifacts:
  - path: '**\*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: 8DCW6dCwDDbsptwVJaAZLnxJCRzqZjHpxShMd6dIfjXBTiD+NqxAF+l0P0hXDdSC
  skip_symbols: true
  artifact: /.*\.nupkg/
